AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: modofun example
Resources:
  modofunExample:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 30
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  ConfigLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - modofunExample
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref modofunExample
      Principal: apigateway.amazonaws.com
Outputs:
  BaseUrl:
    Description: Base URL for the API
    Value: !Join
      - ''
      - - 'https://'
        - !Ref ServerlessRestApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/'
        - !Ref ServerlessRestApiProdStage
        - '/'
