theme: jekyll-theme-dinky
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
title: modofun
description: "Moderate fun with Modular Functions"
show_downloads: false
google_analytics: UA-109618277-1
titles_from_headings:
  enabled: false
author: "Filipe Tavares"
twitter:
  username: fptava
