theme: jekyll-theme-dinky
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
title: modofun
description: "A fast Node.js function router for serverless applications"
show_downloads: false
google_analytics: UA-109618277-1
author: "Filipe Tavares"
twitter:
  username: fptava
logo: https://raw.githubusercontent.com/modofunjs/modofun/master/assets/images/modofun-logo-wide.png
