theme: jekyll-theme-dinky
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
title: modofun
description: "Moderate fun with Modular Functions"
show_downloads: false
titles_from_headings:
  enabled: false
